language: go

go:
  - 1.x
  - 1.12.x
  - 1.13.x
  - master

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

install:
  - gobuilder version -c ">=0.1.5" &>/dev/null || GO111MODULE=auto go get -u -v "github.com/tsaikd/gobuilder"

script:
  - gobuilder --all --check --test

sudo: false
